name: Epic issues for GitHub
description: Automatically update task list when referenced issue is closed
inputs:
  github-token:
    description: GitHub token secret
    required: true
  epic-label-name:
    description: Label name for epic issues
    required: true
    default: epic
  auto-close-epic:
    description: If true when all issues are closed in epic, epic will be closed
    required: true
    default: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: bookmark
  color: purple
