name: Epic issues for GitHub
description: Automatically update task list when referenced issue is closed
inputs:
  github-token:
    description: GitHub token secret
    required: true
  epic-label-name:
    description: Label name for epic issues
    required: true
    default: epic
  close-epic:
    description: When all issues are closed in epic, epic will be closed
    required: true
    default: false
  remove-deleted-issue:
    description: When mentioned issue is deleted its removed from issue list
    required: true
    default: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: bookmark
  color: purple
